# Generated by Django 3.0.5 on 2020-04-26 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateField(default='2020-04-26'),
        ),
    ]
