# Generated by Django 3.0.5 on 2020-04-26 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200426_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateField(default='2020-04-26 19:27'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateField(default='2020-04-26 19:27'),
        ),
    ]
