# Generated by Django 3.0.5 on 2020-04-26 10:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20200426_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.TimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.TimeField(default=datetime.datetime.now),
        ),
    ]
